### ISSUE TITLE
Feature proposal: Push Notification

### ISSUE THREAD

**Issue by 1000ch** [oinume/lekcije#234]
How do you think about [Push Notification](https://developers.google.com/web/fundamentals/push-notifications/) using Service Worker + Push Server (Firebase, OneSignal, etc) as an alternative way to notify?

**Comment by oinume** [comment]
> as an alternative way to notify?

Right now, no. That's because 30% of customers use iOS Safari. PushNotification with ServiceWorker will be one of options for notification if iOS supports ServiceWorker.

I'm thinking about supporting push notification via LINE app.
